//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TimecardApp.TimelogSecurityService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIBase", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Communication.V1_1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.SecurityToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.TimeRegistrationSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.ResponseOfUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimecardApp.TimelogSecurityService.ResponseOfSecurityToken))]
    public partial class APIBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityToken", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    public partial class SecurityToken : TimecardApp.TimelogSecurityService.APIBase {
        
        private string InitialsField;
        
        private System.DateTime ExpiresField;
        
        private string HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Expires {
            get {
                return this.ExpiresField;
            }
            set {
                if ((this.ExpiresField.Equals(value) != true)) {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeRegistrationSettings", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    public partial class TimeRegistrationSettings : TimecardApp.TimelogSecurityService.APIBase {
        
        private bool UseCaseSensetiveLoginField;
        
        private bool UseWBSField;
        
        private bool UseTaskUniqueIDField;
        
        private bool CustomerSortByNoField;
        
        private bool ProjectSortByNoField;
        
        private int FormatingLCIDField;
        
        private bool UseStartEndTimeField;
        
        private bool TimeTrackingShowCustomerNoField;
        
        private bool TimeTrackingShowCustomerNameField;
        
        private bool TimeTrackingShowProjectNoField;
        
        private bool TimeTrackingShowWBSField;
        
        private bool TimeTrackingShowTaskIDField;
        
        private bool AllowTimetrackingOnAllActiveProjectsField;
        
        private bool TimeTrackingAllowRegistrationOverlapField;
        
        private bool ShowTimesheetAdditionalTextFieldField;
        
        private string AdditionalTextFieldLabelField;
        
        private int AdditionalTextFieldValidationField;
        
        private int AdditionalTextFieldTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseCaseSensetiveLogin {
            get {
                return this.UseCaseSensetiveLoginField;
            }
            set {
                if ((this.UseCaseSensetiveLoginField.Equals(value) != true)) {
                    this.UseCaseSensetiveLoginField = value;
                    this.RaisePropertyChanged("UseCaseSensetiveLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseWBS {
            get {
                return this.UseWBSField;
            }
            set {
                if ((this.UseWBSField.Equals(value) != true)) {
                    this.UseWBSField = value;
                    this.RaisePropertyChanged("UseWBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool UseTaskUniqueID {
            get {
                return this.UseTaskUniqueIDField;
            }
            set {
                if ((this.UseTaskUniqueIDField.Equals(value) != true)) {
                    this.UseTaskUniqueIDField = value;
                    this.RaisePropertyChanged("UseTaskUniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool CustomerSortByNo {
            get {
                return this.CustomerSortByNoField;
            }
            set {
                if ((this.CustomerSortByNoField.Equals(value) != true)) {
                    this.CustomerSortByNoField = value;
                    this.RaisePropertyChanged("CustomerSortByNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool ProjectSortByNo {
            get {
                return this.ProjectSortByNoField;
            }
            set {
                if ((this.ProjectSortByNoField.Equals(value) != true)) {
                    this.ProjectSortByNoField = value;
                    this.RaisePropertyChanged("ProjectSortByNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int FormatingLCID {
            get {
                return this.FormatingLCIDField;
            }
            set {
                if ((this.FormatingLCIDField.Equals(value) != true)) {
                    this.FormatingLCIDField = value;
                    this.RaisePropertyChanged("FormatingLCID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool UseStartEndTime {
            get {
                return this.UseStartEndTimeField;
            }
            set {
                if ((this.UseStartEndTimeField.Equals(value) != true)) {
                    this.UseStartEndTimeField = value;
                    this.RaisePropertyChanged("UseStartEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool TimeTrackingShowCustomerNo {
            get {
                return this.TimeTrackingShowCustomerNoField;
            }
            set {
                if ((this.TimeTrackingShowCustomerNoField.Equals(value) != true)) {
                    this.TimeTrackingShowCustomerNoField = value;
                    this.RaisePropertyChanged("TimeTrackingShowCustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool TimeTrackingShowCustomerName {
            get {
                return this.TimeTrackingShowCustomerNameField;
            }
            set {
                if ((this.TimeTrackingShowCustomerNameField.Equals(value) != true)) {
                    this.TimeTrackingShowCustomerNameField = value;
                    this.RaisePropertyChanged("TimeTrackingShowCustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool TimeTrackingShowProjectNo {
            get {
                return this.TimeTrackingShowProjectNoField;
            }
            set {
                if ((this.TimeTrackingShowProjectNoField.Equals(value) != true)) {
                    this.TimeTrackingShowProjectNoField = value;
                    this.RaisePropertyChanged("TimeTrackingShowProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool TimeTrackingShowWBS {
            get {
                return this.TimeTrackingShowWBSField;
            }
            set {
                if ((this.TimeTrackingShowWBSField.Equals(value) != true)) {
                    this.TimeTrackingShowWBSField = value;
                    this.RaisePropertyChanged("TimeTrackingShowWBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool TimeTrackingShowTaskID {
            get {
                return this.TimeTrackingShowTaskIDField;
            }
            set {
                if ((this.TimeTrackingShowTaskIDField.Equals(value) != true)) {
                    this.TimeTrackingShowTaskIDField = value;
                    this.RaisePropertyChanged("TimeTrackingShowTaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool AllowTimetrackingOnAllActiveProjects {
            get {
                return this.AllowTimetrackingOnAllActiveProjectsField;
            }
            set {
                if ((this.AllowTimetrackingOnAllActiveProjectsField.Equals(value) != true)) {
                    this.AllowTimetrackingOnAllActiveProjectsField = value;
                    this.RaisePropertyChanged("AllowTimetrackingOnAllActiveProjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool TimeTrackingAllowRegistrationOverlap {
            get {
                return this.TimeTrackingAllowRegistrationOverlapField;
            }
            set {
                if ((this.TimeTrackingAllowRegistrationOverlapField.Equals(value) != true)) {
                    this.TimeTrackingAllowRegistrationOverlapField = value;
                    this.RaisePropertyChanged("TimeTrackingAllowRegistrationOverlap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool ShowTimesheetAdditionalTextField {
            get {
                return this.ShowTimesheetAdditionalTextFieldField;
            }
            set {
                if ((this.ShowTimesheetAdditionalTextFieldField.Equals(value) != true)) {
                    this.ShowTimesheetAdditionalTextFieldField = value;
                    this.RaisePropertyChanged("ShowTimesheetAdditionalTextField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string AdditionalTextFieldLabel {
            get {
                return this.AdditionalTextFieldLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalTextFieldLabelField, value) != true)) {
                    this.AdditionalTextFieldLabelField = value;
                    this.RaisePropertyChanged("AdditionalTextFieldLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int AdditionalTextFieldValidation {
            get {
                return this.AdditionalTextFieldValidationField;
            }
            set {
                if ((this.AdditionalTextFieldValidationField.Equals(value) != true)) {
                    this.AdditionalTextFieldValidationField = value;
                    this.RaisePropertyChanged("AdditionalTextFieldValidation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int AdditionalTextFieldType {
            get {
                return this.AdditionalTextFieldTypeField;
            }
            set {
                if ((this.AdditionalTextFieldTypeField.Equals(value) != true)) {
                    this.AdditionalTextFieldTypeField = value;
                    this.RaisePropertyChanged("AdditionalTextFieldType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    public partial class User : TimecardApp.TimelogSecurityService.APIBase {
        
        private int IDField;
        
        private string InitialsField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private int LanguageIDField;
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.Role> RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int LanguageID {
            get {
                return this.LanguageIDField;
            }
            set {
                if ((this.LanguageIDField.Equals(value) != true)) {
                    this.LanguageIDField = value;
                    this.RaisePropertyChanged("LanguageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.Role> Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    public partial class Request : TimecardApp.TimelogSecurityService.APIBase {
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.RequestParameter> ParametersField;
        
        private string ServiceClassField;
        
        private string MethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.RequestParameter> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceClass {
            get {
                return this.ServiceClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceClassField, value) != true)) {
                    this.ServiceClassField = value;
                    this.RaisePropertyChanged("ServiceClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfTimeRegistrationSettings", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    public partial class ResponseOfTimeRegistrationSettings : TimecardApp.TimelogSecurityService.APIBase {
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.TimeRegistrationSettings> ReturnField;
        
        private string ReturnTypeDescriptionField;
        
        private TimecardApp.TimelogSecurityService.Request RequestField;
        
        private TimecardApp.TimelogSecurityService.ExecutionStatus ResponseStateField;
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.APIMessage> MessagesField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.TimeRegistrationSettings> Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimecardApp.TimelogSecurityService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimecardApp.TimelogSecurityService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.APIMessage> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfUser", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    public partial class ResponseOfUser : TimecardApp.TimelogSecurityService.APIBase {
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.User> ReturnField;
        
        private string ReturnTypeDescriptionField;
        
        private TimecardApp.TimelogSecurityService.Request RequestField;
        
        private TimecardApp.TimelogSecurityService.ExecutionStatus ResponseStateField;
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.APIMessage> MessagesField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.User> Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimecardApp.TimelogSecurityService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimecardApp.TimelogSecurityService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.APIMessage> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfSecurityToken", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    public partial class ResponseOfSecurityToken : TimecardApp.TimelogSecurityService.APIBase {
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.SecurityToken> ReturnField;
        
        private string ReturnTypeDescriptionField;
        
        private TimecardApp.TimelogSecurityService.Request RequestField;
        
        private TimecardApp.TimelogSecurityService.ExecutionStatus ResponseStateField;
        
        private System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.APIMessage> MessagesField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.SecurityToken> Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimecardApp.TimelogSecurityService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimecardApp.TimelogSecurityService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.ObjectModel.ObservableCollection<TimecardApp.TimelogSecurityService.APIMessage> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionStatus", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Common")]
    public enum ExecutionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessage", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    public partial class APIMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MessageField;
        
        private TimecardApp.TimelogSecurityService.APIMessageSeverity SeverityField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimecardApp.TimelogSecurityService.APIMessageSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Security")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalContractor = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalSalesperson = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TeamLeader = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectMember = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesPerson = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectManager = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LimitedSectionManager = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SectionManager = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAdministrator = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCRM = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserHelpDesk = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserSalary = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAdministration = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectManagement = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerContacts = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeTracking = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanCreateProject = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanEditOwnProjects = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanEditAllProjects = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCanEditOwnDepartmentProjects = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanBeAllocated = 52,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestParameter", Namespace="http://www.timelog.com/api/tlp/v1_1")]
    public partial class RequestParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessageSeverity", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Communication.V1_0")]
    public enum APIMessageSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.timelog.com/api/tlp/v1_2", ConfigurationName="TimelogSecurityService.SecurityService")]
    public interface SecurityService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        System.IAsyncResult BeginIsAlive(System.AsyncCallback callback, object asyncState);
        
        bool EndIsAlive(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetTokenRequest", ReplyAction="GetTokenReponse")]
        System.IAsyncResult BeginGetToken(string user, string password, System.AsyncCallback callback, object asyncState);
        
        TimecardApp.TimelogSecurityService.ResponseOfSecurityToken EndGetToken(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetTimeRegistrationSettingsRequest", ReplyAction="GetTimeRegistrationSettingsReponse")]
        System.IAsyncResult BeginGetTimeRegistrationSettings(TimecardApp.TimelogSecurityService.SecurityToken token, System.AsyncCallback callback, object asyncState);
        
        TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings EndGetTimeRegistrationSettings(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GetUserRequest", ReplyAction="GetUserReponse")]
        System.IAsyncResult BeginGetUser(TimecardApp.TimelogSecurityService.SecurityToken token, System.AsyncCallback callback, object asyncState);
        
        TimecardApp.TimelogSecurityService.ResponseOfUser EndGetUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityServiceChannel : TimecardApp.TimelogSecurityService.SecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IsAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TimecardApp.TimelogSecurityService.ResponseOfSecurityToken Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TimecardApp.TimelogSecurityService.ResponseOfSecurityToken)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTimeRegistrationSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTimeRegistrationSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TimecardApp.TimelogSecurityService.ResponseOfUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TimecardApp.TimelogSecurityService.ResponseOfUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<TimecardApp.TimelogSecurityService.SecurityService>, TimecardApp.TimelogSecurityService.SecurityService {
        
        private BeginOperationDelegate onBeginIsAliveDelegate;
        
        private EndOperationDelegate onEndIsAliveDelegate;
        
        private System.Threading.SendOrPostCallback onIsAliveCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTokenDelegate;
        
        private EndOperationDelegate onEndGetTokenDelegate;
        
        private System.Threading.SendOrPostCallback onGetTokenCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTimeRegistrationSettingsDelegate;
        
        private EndOperationDelegate onEndGetTimeRegistrationSettingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetTimeRegistrationSettingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserDelegate;
        
        private EndOperationDelegate onEndGetUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<IsAliveCompletedEventArgs> IsAliveCompleted;
        
        public event System.EventHandler<GetTokenCompletedEventArgs> GetTokenCompleted;
        
        public event System.EventHandler<GetTimeRegistrationSettingsCompletedEventArgs> GetTimeRegistrationSettingsCompleted;
        
        public event System.EventHandler<GetUserCompletedEventArgs> GetUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TimecardApp.TimelogSecurityService.SecurityService.BeginIsAlive(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIsAlive(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool TimecardApp.TimelogSecurityService.SecurityService.EndIsAlive(System.IAsyncResult result) {
            return base.Channel.EndIsAlive(result);
        }
        
        private System.IAsyncResult OnBeginIsAlive(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TimecardApp.TimelogSecurityService.SecurityService)(this)).BeginIsAlive(callback, asyncState);
        }
        
        private object[] OnEndIsAlive(System.IAsyncResult result) {
            bool retVal = ((TimecardApp.TimelogSecurityService.SecurityService)(this)).EndIsAlive(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIsAliveCompleted(object state) {
            if ((this.IsAliveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IsAliveCompleted(this, new IsAliveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IsAliveAsync() {
            this.IsAliveAsync(null);
        }
        
        public void IsAliveAsync(object userState) {
            if ((this.onBeginIsAliveDelegate == null)) {
                this.onBeginIsAliveDelegate = new BeginOperationDelegate(this.OnBeginIsAlive);
            }
            if ((this.onEndIsAliveDelegate == null)) {
                this.onEndIsAliveDelegate = new EndOperationDelegate(this.OnEndIsAlive);
            }
            if ((this.onIsAliveCompletedDelegate == null)) {
                this.onIsAliveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIsAliveCompleted);
            }
            base.InvokeAsync(this.onBeginIsAliveDelegate, null, this.onEndIsAliveDelegate, this.onIsAliveCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TimecardApp.TimelogSecurityService.SecurityService.BeginGetToken(string user, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetToken(user, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimecardApp.TimelogSecurityService.ResponseOfSecurityToken TimecardApp.TimelogSecurityService.SecurityService.EndGetToken(System.IAsyncResult result) {
            return base.Channel.EndGetToken(result);
        }
        
        private System.IAsyncResult OnBeginGetToken(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((TimecardApp.TimelogSecurityService.SecurityService)(this)).BeginGetToken(user, password, callback, asyncState);
        }
        
        private object[] OnEndGetToken(System.IAsyncResult result) {
            TimecardApp.TimelogSecurityService.ResponseOfSecurityToken retVal = ((TimecardApp.TimelogSecurityService.SecurityService)(this)).EndGetToken(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTokenCompleted(object state) {
            if ((this.GetTokenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTokenCompleted(this, new GetTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTokenAsync(string user, string password) {
            this.GetTokenAsync(user, password, null);
        }
        
        public void GetTokenAsync(string user, string password, object userState) {
            if ((this.onBeginGetTokenDelegate == null)) {
                this.onBeginGetTokenDelegate = new BeginOperationDelegate(this.OnBeginGetToken);
            }
            if ((this.onEndGetTokenDelegate == null)) {
                this.onEndGetTokenDelegate = new EndOperationDelegate(this.OnEndGetToken);
            }
            if ((this.onGetTokenCompletedDelegate == null)) {
                this.onGetTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTokenCompleted);
            }
            base.InvokeAsync(this.onBeginGetTokenDelegate, new object[] {
                        user,
                        password}, this.onEndGetTokenDelegate, this.onGetTokenCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TimecardApp.TimelogSecurityService.SecurityService.BeginGetTimeRegistrationSettings(TimecardApp.TimelogSecurityService.SecurityToken token, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTimeRegistrationSettings(token, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings TimecardApp.TimelogSecurityService.SecurityService.EndGetTimeRegistrationSettings(System.IAsyncResult result) {
            return base.Channel.EndGetTimeRegistrationSettings(result);
        }
        
        private System.IAsyncResult OnBeginGetTimeRegistrationSettings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TimecardApp.TimelogSecurityService.SecurityToken token = ((TimecardApp.TimelogSecurityService.SecurityToken)(inValues[0]));
            return ((TimecardApp.TimelogSecurityService.SecurityService)(this)).BeginGetTimeRegistrationSettings(token, callback, asyncState);
        }
        
        private object[] OnEndGetTimeRegistrationSettings(System.IAsyncResult result) {
            TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings retVal = ((TimecardApp.TimelogSecurityService.SecurityService)(this)).EndGetTimeRegistrationSettings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTimeRegistrationSettingsCompleted(object state) {
            if ((this.GetTimeRegistrationSettingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTimeRegistrationSettingsCompleted(this, new GetTimeRegistrationSettingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTimeRegistrationSettingsAsync(TimecardApp.TimelogSecurityService.SecurityToken token) {
            this.GetTimeRegistrationSettingsAsync(token, null);
        }
        
        public void GetTimeRegistrationSettingsAsync(TimecardApp.TimelogSecurityService.SecurityToken token, object userState) {
            if ((this.onBeginGetTimeRegistrationSettingsDelegate == null)) {
                this.onBeginGetTimeRegistrationSettingsDelegate = new BeginOperationDelegate(this.OnBeginGetTimeRegistrationSettings);
            }
            if ((this.onEndGetTimeRegistrationSettingsDelegate == null)) {
                this.onEndGetTimeRegistrationSettingsDelegate = new EndOperationDelegate(this.OnEndGetTimeRegistrationSettings);
            }
            if ((this.onGetTimeRegistrationSettingsCompletedDelegate == null)) {
                this.onGetTimeRegistrationSettingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTimeRegistrationSettingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetTimeRegistrationSettingsDelegate, new object[] {
                        token}, this.onEndGetTimeRegistrationSettingsDelegate, this.onGetTimeRegistrationSettingsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TimecardApp.TimelogSecurityService.SecurityService.BeginGetUser(TimecardApp.TimelogSecurityService.SecurityToken token, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUser(token, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimecardApp.TimelogSecurityService.ResponseOfUser TimecardApp.TimelogSecurityService.SecurityService.EndGetUser(System.IAsyncResult result) {
            return base.Channel.EndGetUser(result);
        }
        
        private System.IAsyncResult OnBeginGetUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TimecardApp.TimelogSecurityService.SecurityToken token = ((TimecardApp.TimelogSecurityService.SecurityToken)(inValues[0]));
            return ((TimecardApp.TimelogSecurityService.SecurityService)(this)).BeginGetUser(token, callback, asyncState);
        }
        
        private object[] OnEndGetUser(System.IAsyncResult result) {
            TimecardApp.TimelogSecurityService.ResponseOfUser retVal = ((TimecardApp.TimelogSecurityService.SecurityService)(this)).EndGetUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserCompleted(object state) {
            if ((this.GetUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserAsync(TimecardApp.TimelogSecurityService.SecurityToken token) {
            this.GetUserAsync(token, null);
        }
        
        public void GetUserAsync(TimecardApp.TimelogSecurityService.SecurityToken token, object userState) {
            if ((this.onBeginGetUserDelegate == null)) {
                this.onBeginGetUserDelegate = new BeginOperationDelegate(this.OnBeginGetUser);
            }
            if ((this.onEndGetUserDelegate == null)) {
                this.onEndGetUserDelegate = new EndOperationDelegate(this.OnEndGetUser);
            }
            if ((this.onGetUserCompletedDelegate == null)) {
                this.onGetUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserDelegate, new object[] {
                        token}, this.onEndGetUserDelegate, this.onGetUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TimecardApp.TimelogSecurityService.SecurityService CreateChannel() {
            return new SecurityServiceClientChannel(this);
        }
        
        private class SecurityServiceClientChannel : ChannelBase<TimecardApp.TimelogSecurityService.SecurityService>, TimecardApp.TimelogSecurityService.SecurityService {
            
            public SecurityServiceClientChannel(System.ServiceModel.ClientBase<TimecardApp.TimelogSecurityService.SecurityService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginIsAlive(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("IsAlive", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndIsAlive(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("IsAlive", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetToken(string user, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = user;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("GetToken", _args, callback, asyncState);
                return _result;
            }
            
            public TimecardApp.TimelogSecurityService.ResponseOfSecurityToken EndGetToken(System.IAsyncResult result) {
                object[] _args = new object[0];
                TimecardApp.TimelogSecurityService.ResponseOfSecurityToken _result = ((TimecardApp.TimelogSecurityService.ResponseOfSecurityToken)(base.EndInvoke("GetToken", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTimeRegistrationSettings(TimecardApp.TimelogSecurityService.SecurityToken token, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = token;
                System.IAsyncResult _result = base.BeginInvoke("GetTimeRegistrationSettings", _args, callback, asyncState);
                return _result;
            }
            
            public TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings EndGetTimeRegistrationSettings(System.IAsyncResult result) {
                object[] _args = new object[0];
                TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings _result = ((TimecardApp.TimelogSecurityService.ResponseOfTimeRegistrationSettings)(base.EndInvoke("GetTimeRegistrationSettings", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUser(TimecardApp.TimelogSecurityService.SecurityToken token, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = token;
                System.IAsyncResult _result = base.BeginInvoke("GetUser", _args, callback, asyncState);
                return _result;
            }
            
            public TimecardApp.TimelogSecurityService.ResponseOfUser EndGetUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                TimecardApp.TimelogSecurityService.ResponseOfUser _result = ((TimecardApp.TimelogSecurityService.ResponseOfUser)(base.EndInvoke("GetUser", _args, result)));
                return _result;
            }
        }
    }
}
